# docker-compose.yml
services:
  postgres:
    image: postgres:18-alpine
    container_name: payroll_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payroll_db
    ports:
      - "5432:5432"
    volumes:
      - payroll_postgres_data:/var/lib/postgresql/data

volumes:
  payroll_postgres_data: